// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdpdxncagetfozefswed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcGR4bmNhZ2V0Zm96ZWZzd2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjc5MDUsImV4cCI6MjA2OTcwMzkwNX0.hfSSOKuYsZFV-9o6fs1VzQ_SekQ3nDdPj3xj-fQBL1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});